import Foundation

/// Writes per-disk markdown report and appends a row to INDEX.md,
/// matching the existing ~/disk-reports layout.
enum Reporter {
    static var dir: String { Paths.reportsDir }
    static var indexPath: String { (dir as NSString).appendingPathComponent("INDEX.md") }

    struct Outcome {
        let disk: DiskInfo
        let mode: String          // "full" or "quick"
        let pre: SmartSnapshot
        let post: SmartSnapshot
        let eraseSummary: String
        let verifySummary: String
        let longTestSummary: String
        let verdict: String       // emoji + words
        let date: String
    }

    /// Writes the detail file + index row. Returns the path actually written
    /// (or empty string on failure) so `main.swift` can surface the result.
    /// All write errors are now logged (QA-fix: previously `try?` swallowed them).
    @discardableResult
    static func write(_ o: Outcome) -> String {
        do {
            try FileManager.default.createDirectory(atPath: dir, withIntermediateDirectories: true)
        } catch {
            Logger.error("reporter", "mkdir \(dir) failed: \(error.localizedDescription)")
            return ""
        }
        ensureIndexHeader()
        let path = writeDetail(o)
        appendIndexRow(o)
        return path
    }

    private static func ensureIndexHeader() {
        if !FileManager.default.fileExists(atPath: indexPath) {
            let header = """
            # Disk Test Reports — Index

            | Date | Model | Serial | Capacity | Interface | Power-On (h) | Wear | SMART | Erase | Verify | Verdict | Report |
            |------|-------|--------|----------|-----------|--------------|------|-------|-------|--------|---------|--------|

            """
            do {
                try header.write(toFile: indexPath, atomically: true, encoding: .utf8)
                Paths.chownToUser(indexPath)
            } catch {
                Logger.error("reporter", "INDEX.md header write failed: \(error.localizedDescription)")
            }
        }
    }

    private static func detailPath(_ serial: String) -> String {
        let safe = serial.isEmpty ? "unknown-\(Int(Date().timeIntervalSince1970))" : serial
        return (dir as NSString).appendingPathComponent("\(safe).md")
    }

    /// Returns the written path, or "" on failure.
    @discardableResult
    private static func writeDetail(_ o: Outcome) -> String {
        func b(_ v: Int?) -> String { v.map(String.init) ?? "—" }
        let wear = o.post.wearValueNormalized.map { "VALUE \($0)" } ?? "—"
        let md = """
        # Disk Report — \(o.disk.model)

        **Serial:** \(o.disk.serial)
        **Tested:** \(o.date)
        **Mode:** \(o.mode) erase
        **Verdict:** \(o.verdict)

        ## Identity

        | Field | Value |
        |-------|-------|
        | Model | \(o.disk.model) |
        | Serial | \(o.disk.serial) |
        | Firmware | \(o.disk.firmware) |
        | Capacity | \(o.disk.sizeBytes) bytes (\(String(format: "%.1f", o.disk.sizeGB)) GB) |
        | Type | \(o.disk.isSSD ? "SSD" : "HDD") |
        | Interface | \(o.disk.busProtocol) |
        | Block size | \(o.disk.blockSize) B |

        ## Health (before → after)

        | Attribute | Before | After |
        |-----------|--------|-------|
        | SMART health | \(o.pre.healthPassed.map { $0 ? "PASSED" : "FAILED" } ?? "—") | \(o.post.healthPassed.map { $0 ? "PASSED" : "FAILED" } ?? "—") |
        | Power-On Hours | \(b(o.pre.powerOnHours)) | \(b(o.post.powerOnHours)) |
        | Power Cycles | \(b(o.pre.powerCycles)) | \(b(o.post.powerCycles)) |
        | Wear (norm.) | \(o.pre.wearValueNormalized.map { "VALUE \($0)" } ?? "—") | \(wear) |
        | Reallocated | \(b(o.pre.reallocated)) | \(b(o.post.reallocated)) |
        | Pending | \(b(o.pre.pending)) | \(b(o.post.pending)) |
        | Offline Uncorrectable | \(b(o.pre.offlineUncorrectable)) | \(b(o.post.offlineUncorrectable)) |
        | Reported Uncorrect | \(b(o.pre.reportedUncorrect)) | \(b(o.post.reportedUncorrect)) |
        | UDMA CRC Errors | \(b(o.pre.crcErrors)) | \(b(o.post.crcErrors)) |
        | Command Timeout | \(b(o.pre.commandTimeout)) | \(b(o.post.commandTimeout)) |
        | Temperature °C | \(b(o.pre.temperatureC)) | \(b(o.post.temperatureC)) |

        ## Operations

        | Step | Result |
        |------|--------|
        | Erase (\(o.mode)) | \(o.eraseSummary) |
        | Verify-read | \(o.verifySummary) |
        | SMART long self-test | \(o.longTestSummary) |
        | Final partition map | Empty GPT (no filesystem) |

        _Generated by diskwipe-engine._
        """
        let path = detailPath(o.disk.serial)
        do {
            try md.write(toFile: path, atomically: true, encoding: .utf8)
            Paths.chownToUser(path)
            return path
        } catch {
            Logger.error("reporter", "detail write failed at \(path): \(error.localizedDescription)")
            return ""
        }
    }

    private static func appendIndexRow(_ o: Outcome) {
        let wear = o.post.wearValueNormalized.map { "VALUE \($0)" } ?? "—"
        let serialFile = o.disk.serial.isEmpty ? "unknown" : o.disk.serial
        let row = "| \(o.date) | \(o.disk.model) | \(o.disk.serial) | "
            + "\(String(format: "%.1f", o.disk.sizeGB)) GB | \(o.disk.busProtocol) | "
            + "\(o.post.powerOnHours.map(String.init) ?? "—") | \(wear) | "
            + "\(o.post.healthPassed.map { $0 ? "PASSED" : "FAILED" } ?? "—") | "
            + "\(o.eraseSummary) | \(o.verifySummary) | \(o.verdict) | [link](\(serialFile).md) |\n"
        guard let rowData = row.data(using: .utf8) else {
            Logger.error("reporter", "INDEX row encoding failed (non-UTF-8?)")
            return
        }
        guard let fh = FileHandle(forWritingAtPath: indexPath) else {
            Logger.error("reporter", "INDEX.md open-for-append failed (missing or unwritable)")
            return
        }
        fh.seekToEndOfFile()
        do {
            try fh.write(contentsOf: rowData)
            try fh.close()
        } catch {
            Logger.error("reporter", "INDEX row write failed: \(error.localizedDescription)")
            try? fh.close()
        }
    }
}
